print('THIS PROGRAM IS BUILT TO MAKE SHOW HOW TO BUILD A PLANE WITH PROP ALONG WITH THE EDITING OF THESE SET COMPONENTS WHICH WILL BE CREATED')
print()
print('I DECIDED TO ADD A TWIST TO THE CHALLENGE AND THAT IS THAT I WILL BE MODELING IT AFTER A ROUGH MODEL OF THE CESSNA 172 SKYHAWK')
print()

import openvsp as vsp
vsp.ClearVSPModel();

# 1. Using the OpenVSP Python API you just set up, create a python script that automatically creates a fuselage,
#a wing, a horizontal tail, and a vertical tail, and have it place them in reasonable locations.
print()
print('This Cessna 172 Skyhawk Model is based off of some design publicly available in which I overlayed using the background tool and roughly sketched the Fuselage')
print()
#Fuselage
fuse_id = vsp.AddGeom('FUSELAGE','')
fuselen_id = vsp.GetParm(fuse_id,'Length','Design')
vsp.SetParmVal(fuselen_id, 25.20)
vsp.SetParmVal( fuse_id, "TBSym",'XSec_0', 0)
vsp.SetParmVal( fuse_id, 'TopLRAngleEq', 'XSec_0', 0)

#Section 0 of the Fuselage (XSec & Skinning)
vsp.SetParmVal(fuse_id,'ZLocPercent','XSec_0', 0.0330)
vsp.SetParmVal(fuse_id,'TopLAngle', 'XSec_0', 20.0)
vsp.SetParmVal(fuse_id,'TopLStrength', 'XSec_0', 0.80)
vsp.SetParmVal(fuse_id,'RightLAngle', 'XSec_0', 50.0)
vsp.SetParmVal(fuse_id,'RightLStrength', 'XSec_0', 1.0)
vsp.SetParmVal(fuse_id,'BottomLStrength', 'XSec_0', 0.5)
vsp.SetParmVal(fuse_id,'BottomLAngle', 'XSec_0', 50.0)
vsp.SetParmVal(fuse_id,'LeftLAngle', 'XSec_0', 50.0)
vsp.SetParmVal(fuse_id,'LeftLStrength', 'XSec_0', 1.0)

#Section 1 of Fuselage
# XSec
xsurf_id = vsp.GetXSecSurf(fuse_id, 1)
vsp.ChangeXSecShape(xsurf_id, 1, vsp.XS_SUPER_ELLIPSE)
xsec1_id = vsp.GetXSec(xsurf_id, 1)
toplrangleeq1_id = vsp.GetXSecParm(xsec1_id, 'TopLRAngleEq')
bottomlrangleeq1_id = vsp.GetXSecParm(xsec1_id, 'BottomLRAngleEq')
tbsym1_id = vsp.GetXSecParm(xsec1_id, 'TBSym')
width1_id = vsp.GetXSecParm(xsec1_id,'Super_Width')
height1_id = vsp.GetXSecParm(xsec1_id, 'Super_Height')
secttess1_id = vsp.GetXSecParm(xsec1_id, 'SectTess_U')
xlocpercent1_id = vsp.GetXSecParm(xsec1_id, 'XLocPercent')
zlocpercent1_id = vsp.GetXSecParm(xsec1_id, 'ZLocPercent')
supermaxwidthloc1_id = vsp.GetXSecParm(xsec1_id,'Super_MaxWidthLoc')
superm1_id = vsp.GetXSecParm(xsec1_id,'Super_M')
supern1_id = vsp.GetXSecParm(xsec1_id, 'Super_N')
vsp.SetParmVal(width1_id, 2.35)
vsp.SetParmVal(height1_id, 1.0)
vsp.SetParmVal(secttess1_id, 15)
vsp.SetParmVal(xlocpercent1_id, 0.0550)
vsp.SetParmVal(zlocpercent1_id, 0.0250)
vsp.SetParmVal(supermaxwidthloc1_id, 0.290)
vsp.SetParmVal(superm1_id, 2.0)
vsp.SetParmVal(supern1_id, 2.0)
vsp.SetParmVal(tbsym1_id, 0)
vsp.SetParmVal(toplrangleeq1_id, 0)
vsp.SetParmVal(bottomlrangleeq1_id, 0)

# Skinning Left
toplangle1_id = vsp.GetXSecParm(xsec1_id, 'TopLAngle')
toplstrength1_id = vsp.GetXSecParm(xsec1_id, 'TopLStrength')
rightlangle1_id = vsp.GetXSecParm(xsec1_id, 'RightLAngle')
rightlstrength1_id = vsp.GetXSecParm(xsec1_id, 'RightLStrength')
bottomlangle1_id = vsp.GetXSecParm(xsec1_id, 'BottomLAngle')
bottomlstrength1_id = vsp.GetXSecParm(xsec1_id, 'BottomLStrength')
leftlangle1_id = vsp.GetXSecParm(xsec1_id, 'LeftLAngle')
leftlstrength1_id =  vsp.GetXSecParm(xsec1_id, 'LeftLStrength')
vsp.SetParmVal(toplangle1_id, 23.0)
vsp.SetParmVal(toplstrength1_id, 0.01)
vsp.SetParmVal(rightlangle1_id, 88.0)
vsp.SetParmVal(rightlstrength1_id, 1.95)
vsp.SetParmVal(bottomlstrength1_id, 0.01)
vsp.SetParmVal(bottomlangle1_id, 20.0)
vsp.SetParmVal(leftlangle1_id, 88.0)
vsp.SetParmVal(leftlstrength1_id, 1.95)

# Skinning Right
toprangle1_id = vsp.GetXSecParm(xsec1_id, 'TopRAngle')
toprstrength1_id = vsp.GetXSecParm(xsec1_id, 'TopRStrength')
rightrangle1_id = vsp.GetXSecParm(xsec1_id, 'RightRAngle')
rightrstrength1_id = vsp.GetXSecParm(xsec1_id, 'RightRStrength')
bottomrangle1_id = vsp.GetXSecParm(xsec1_id, 'BottomRAngle')
bottomrstrength1_id = vsp.GetXSecParm(xsec1_id, 'BottomRStrength')
leftrangle1_id = vsp.GetXSecParm(xsec1_id, 'LeftRAngle')
leftrstrength1_id =  vsp.GetXSecParm(xsec1_id, 'LeftRStrength')
vsp.SetParmVal(toprangle1_id, 37.5)
vsp.SetParmVal(toprstrength1_id, 1.0)
vsp.SetParmVal(rightrangle1_id, 88.0)
vsp.SetParmVal(rightrstrength1_id, 1.0)
vsp.SetParmVal(bottomrstrength1_id, 4.0)
vsp.SetParmVal(bottomrangle1_id, 75.0)
vsp.SetParmVal(leftrangle1_id, 88.0)
vsp.SetParmVal(leftrstrength1_id, 1.0)

#Section 2 of Fuselage
# XSec
xsurf_id = vsp.GetXSecSurf(fuse_id, 2)
vsp.ChangeXSecShape(xsurf_id, 2, vsp.XS_SUPER_ELLIPSE)
xsec2_id = vsp.GetXSec(xsurf_id, 2)
toplrangleeq2_id = vsp.GetXSecParm(xsec2_id, 'TopLRAngleEq')
bottomlrangleeq2_id = vsp.GetXSecParm(xsec2_id, 'BottomLRAngleEq')
tbsym2_id = vsp.GetXSecParm(xsec2_id, 'TBSym')
width2_id = vsp.GetXSecParm(xsec2_id,'Super_Width')
height2_id = vsp.GetXSecParm(xsec2_id, 'Super_Height')
secttess2_id = vsp.GetXSecParm(xsec2_id, 'SectTess_U')
xlocpercent2_id = vsp.GetXSecParm(xsec2_id, 'XLocPercent')
supermaxwidthloc2_id = vsp.GetXSecParm(xsec2_id,'Super_MaxWidthLoc')
superm2_id = vsp.GetXSecParm(xsec2_id,'Super_M')
supern2_id = vsp.GetXSecParm(xsec2_id, 'Super_N')
vsp.SetParmVal(width2_id, 3.6)
vsp.SetParmVal(height2_id, 3.65)
vsp.SetParmVal(secttess2_id, 15)
vsp.SetParmVal(xlocpercent2_id, 0.21)
vsp.SetParmVal(supermaxwidthloc2_id, 0.290)
vsp.SetParmVal(superm2_id, 2.0)
vsp.SetParmVal(supern2_id, 2.0)
vsp.SetParmVal(tbsym2_id, 0)
vsp.SetParmVal(toplrangleeq2_id, 0)
vsp.SetParmVal(bottomlrangleeq2_id, 0)

# Skinning Left
toplangle2_id = vsp.GetXSecParm(xsec2_id, 'TopLAngle')
toplstrength2_id = vsp.GetXSecParm(xsec2_id, 'TopLStrength')
rightlangle2_id = vsp.GetXSecParm(xsec2_id, 'RightLAngle')
rightlstrength2_id = vsp.GetXSecParm(xsec2_id, 'RightLStrength')
bottomlangle2_id = vsp.GetXSecParm(xsec2_id, 'BottomLAngle')
bottomlstrength2_id = vsp.GetXSecParm(xsec2_id, 'BottomLStrength')
leftlangle2_id = vsp.GetXSecParm(xsec2_id, 'LeftLAngle')
leftlstrength2_id =  vsp.GetXSecParm(xsec2_id, 'LeftLStrength')
vsp.SetParmVal(toplangle2_id, 20.0)
vsp.SetParmVal(toplstrength2_id, 0.01)
vsp.SetParmVal(rightlangle2_id, 0.0)
vsp.SetParmVal(rightlstrength2_id, 1.0)
vsp.SetParmVal(bottomlstrength2_id, 0.18)
vsp.SetParmVal(bottomlangle2_id, 120.0)
vsp.SetParmVal(leftlangle2_id, 0.0)
vsp.SetParmVal(leftlstrength2_id, 1.0)

# Skinning Right
toprangle2_id = vsp.GetXSecParm(xsec2_id, 'TopRAngle')
toprstrength2_id = vsp.GetXSecParm(xsec2_id, 'TopRStrength')
rightrangle2_id = vsp.GetXSecParm(xsec2_id, 'RightRAngle')
rightrstrength2_id = vsp.GetXSecParm(xsec2_id, 'RightRStrength')
bottomrangle2_id = vsp.GetXSecParm(xsec2_id, 'BottomRAngle')
bottomrstrength2_id = vsp.GetXSecParm(xsec2_id, 'BottomRStrength')
leftrangle2_id = vsp.GetXSecParm(xsec2_id, 'LeftRAngle')
leftrstrength2_id =  vsp.GetXSecParm(xsec2_id, 'LeftRStrength')
vsp.SetParmVal(toprangle2_id, 43.0)
vsp.SetParmVal(toprstrength2_id, 0.88)
vsp.SetParmVal(rightrangle2_id, 0.0)
vsp.SetParmVal(rightrstrength2_id, 1.0)
vsp.SetParmVal(bottomrstrength2_id, 0.25)
vsp.SetParmVal(bottomrangle2_id, 35.0)
vsp.SetParmVal(leftrangle2_id, 0.0)
vsp.SetParmVal(leftrstrength2_id, 1.0)

#Section 3 of Fuselage
# XSec
xsurf_id = vsp.GetXSecSurf(fuse_id, 3)
vsp.ChangeXSecShape(xsurf_id, 3, vsp.XS_GENERAL_FUSE)
xsec3_id = vsp.GetXSec(xsurf_id, 3)
toplrangleeq3_id = vsp.GetXSecParm(xsec3_id, 'TopLRAngleEq')
bottomlrangleeq3_id = vsp.GetXSecParm(xsec3_id, 'BottomLRAngleEq')
tbsym3_id = vsp.GetXSecParm(xsec3_id, 'TBSym')
width3_id = vsp.GetXSecParm(xsec3_id,'Width')
height3_id = vsp.GetXSecParm(xsec3_id, 'Height')
secttess3_id = vsp.GetXSecParm(xsec3_id, 'SectTess_U')
xlocpercent3_id = vsp.GetXSecParm(xsec3_id, 'XLocPercent')
zlocpercent3_id = vsp.GetXSecParm(xsec3_id, 'ZLocPercent')
supermaxwidthloc3_id = vsp.GetXSecParm(xsec3_id,'MaxWidthLoc')
topstr3_id = vsp.GetXSecParm(xsec3_id,'TopStr')
botstr3_id = vsp.GetXSecParm(xsec3_id,'BotStr')
upstr3_id = vsp.GetXSecParm(xsec3_id,'UpStr')
lowstr3_id = vsp.GetXSecParm(xsec3_id,'LowStr')
vsp.SetParmVal(width3_id, 3.8)
vsp.SetParmVal(height3_id, 5.20)
vsp.SetParmVal(secttess3_id, 8)
vsp.SetParmVal(xlocpercent3_id, 0.30)
vsp.SetParmVal(zlocpercent3_id, 0.025)
vsp.SetParmVal(supermaxwidthloc3_id, 0.0)
vsp.SetParmVal(topstr3_id, 2.0)
vsp.SetParmVal(botstr3_id, 1.5)
vsp.SetParmVal(upstr3_id, 1.5)
vsp.SetParmVal(lowstr3_id, 1.0)
vsp.SetParmVal(tbsym3_id, 0)
vsp.SetParmVal(toplrangleeq3_id, 0)
vsp.SetParmVal(bottomlrangleeq3_id, 0)

# Skinning Left
toplangle3_id = vsp.GetXSecParm(xsec3_id, 'TopLAngle')
toplstrength3_id = vsp.GetXSecParm(xsec3_id, 'TopLStrength')
rightlangle3_id = vsp.GetXSecParm(xsec3_id, 'RightLAngle')
rightlstrength3_id = vsp.GetXSecParm(xsec3_id, 'RightLStrength')
bottomlangle3_id = vsp.GetXSecParm(xsec3_id, 'BottomLAngle')
bottomlstrength3_id = vsp.GetXSecParm(xsec3_id, 'BottomLStrength')
leftlangle3_id = vsp.GetXSecParm(xsec3_id, 'LeftLAngle')
leftlstrength3_id =  vsp.GetXSecParm(xsec3_id, 'LeftLStrength')
vsp.SetParmVal(toplangle3_id, 21.0)
vsp.SetParmVal(toplstrength3_id, 1.30)
vsp.SetParmVal(rightlangle3_id, 0.0)
vsp.SetParmVal(rightlstrength3_id, 1.0)
vsp.SetParmVal(bottomlstrength3_id, 0.75)
vsp.SetParmVal(bottomlangle3_id, 9.5)
vsp.SetParmVal(leftlangle3_id, 0.0)
vsp.SetParmVal(leftlstrength3_id, 1.0)
# Skinning Right
toprangle3_id = vsp.GetXSecParm(xsec3_id, 'TopRAngle')
toprstrength3_id = vsp.GetXSecParm(xsec3_id, 'TopRStrength')
rightrangle3_id = vsp.GetXSecParm(xsec3_id, 'RightRAngle')
rightrstrength3_id = vsp.GetXSecParm(xsec3_id, 'RightRStrength')
bottomrangle3_id = vsp.GetXSecParm(xsec3_id, 'BottomRAngle')
bottomrstrength3_id = vsp.GetXSecParm(xsec3_id, 'BottomRStrength')
leftrangle3_id = vsp.GetXSecParm(xsec3_id, 'LeftRAngle')
leftrstrength3_id =  vsp.GetXSecParm(xsec3_id, 'LeftRStrength')
vsp.SetParmVal(toprangle3_id, 15.0)
vsp.SetParmVal(toprstrength3_id, 1.15)
vsp.SetParmVal(rightrangle3_id, 0.0)
vsp.SetParmVal(rightrstrength3_id, 1.0)
vsp.SetParmVal(bottomrstrength3_id, 5.50)
vsp.SetParmVal(bottomrangle3_id, -1.50)
vsp.SetParmVal(leftrangle3_id, 0.0)
vsp.SetParmVal(leftrstrength3_id, 1.0)
vsp.InsertXSec( fuse_id, 3, vsp.XS_SUPER_ELLIPSE)

# Section 4 of Fuselage
# XSec
xsurf_id = vsp.GetXSecSurf(fuse_id, 4)
vsp.ChangeXSecShape(xsurf_id, 4, vsp.XS_GENERAL_FUSE)
xsec4_id = vsp.GetXSec(xsurf_id, 4)
toplrangleeq4_id = vsp.GetXSecParm(xsec4_id, 'TopLRAngleEq')
bottomlrangleeq4_id = vsp.GetXSecParm(xsec4_id, 'BottomLRAngleEq')
tbsym4_id = vsp.GetXSecParm(xsec4_id, 'TBSym')
width4_id = vsp.GetXSecParm(xsec4_id,'Width')
height4_id = vsp.GetXSecParm(xsec4_id, 'Height')
secttess4_id = vsp.GetXSecParm(xsec4_id, 'SectTess_U')
xlocpercent4_id = vsp.GetXSecParm(xsec4_id, 'XLocPercent')
zlocpercent4_id = vsp.GetXSecParm(xsec4_id, 'ZLocPercent')
topstr4_id = vsp.GetXSecParm(xsec4_id,'TopStr')
botstr4_id = vsp.GetXSecParm(xsec4_id,'BotStr')
upstr4_id = vsp.GetXSecParm(xsec4_id,'UpStr')
lowstr4_id = vsp.GetXSecParm(xsec4_id,'LowStr')
vsp.SetParmVal(width4_id, 3.75)
vsp.SetParmVal(height4_id, 3.85)
vsp.SetParmVal(secttess4_id, 15)
vsp.SetParmVal(xlocpercent4_id, 0.512)
vsp.SetParmVal(zlocpercent4_id, 0.011)
vsp.SetParmVal(topstr4_id, 1.5)
vsp.SetParmVal(botstr4_id, 1.5)
vsp.SetParmVal(upstr4_id, 1.5)
vsp.SetParmVal(lowstr4_id, 1.5)
vsp.SetParmVal(tbsym4_id, 0)
vsp.SetParmVal(toplrangleeq4_id, 0)
vsp.SetParmVal(bottomlrangleeq4_id, 0)

# Skinning Left
toplangle4_id = vsp.GetXSecParm(xsec4_id, 'TopLAngle')
toplstrength4_id = vsp.GetXSecParm(xsec4_id, 'TopLStrength')
rightlangle4_id = vsp.GetXSecParm(xsec4_id, 'RightLAngle')
rightlstrength4_id = vsp.GetXSecParm(xsec4_id, 'RightLStrength')
bottomlangle4_id = vsp.GetXSecParm(xsec4_id, 'BottomLAngle')
bottomlstrength4_id = vsp.GetXSecParm(xsec4_id, 'BottomLStrength')
leftlangle4_id = vsp.GetXSecParm(xsec4_id, 'LeftLAngle')
leftlstrength4_id =  vsp.GetXSecParm(xsec4_id, 'LeftLStrength')
vsp.SetParmVal(toplangle4_id, -40.0)
vsp.SetParmVal(toplstrength4_id, 1.20)
vsp.SetParmVal(rightlangle4_id, 0.0)
vsp.SetParmVal(rightlstrength4_id, 1.0)
vsp.SetParmVal(bottomlangle4_id, 0.0)
vsp.SetParmVal(bottomlstrength4_id, 1.0)
vsp.SetParmVal(leftlangle4_id, 0.0)
vsp.SetParmVal(leftlstrength4_id, 1.0)

# Skinning Right
toprangle4_id = vsp.GetXSecParm(xsec4_id, 'TopRAngle')
toprstrength4_id = vsp.GetXSecParm(xsec4_id, 'TopRStrength')
rightrangle4_id = vsp.GetXSecParm(xsec4_id, 'RightRAngle')
rightrstrength4_id = vsp.GetXSecParm(xsec4_id, 'RightRStrength')
bottomrangle4_id = vsp.GetXSecParm(xsec4_id, 'BottomRAngle')
bottomrstrength4_id = vsp.GetXSecParm(xsec4_id, 'BottomRStrength')
leftrangle4_id = vsp.GetXSecParm(xsec4_id, 'LeftRAngle')
leftrstrength4_id =  vsp.GetXSecParm(xsec4_id, 'LeftRStrength')
vsp.SetParmVal(toprangle4_id, -18.0)
vsp.SetParmVal(toprstrength4_id, 1.26)
vsp.SetParmVal(rightrangle4_id, 0.0)
vsp.SetParmVal(rightrstrength4_id, 1.0)
vsp.SetParmVal(bottomrangle4_id, -16.0)
vsp.SetParmVal(bottomrstrength4_id, 1.0)
vsp.SetParmVal(leftrangle4_id, 0.0)
vsp.SetParmVal(leftrstrength4_id, 1.0)
vsp.InsertXSec( fuse_id, 4, vsp.XS_SUPER_ELLIPSE)

# Section 5 of Fuselage
# XSec
xsurf_id = vsp.GetXSecSurf(fuse_id, 5)
xsec5_id = vsp.GetXSec(xsurf_id, 5)
toplrangleeq5_id = vsp.GetXSecParm(xsec5_id, 'TopLRAngleEq')
bottomlrangleeq5_id = vsp.GetXSecParm(xsec5_id, 'BottomLRAngleEq')
tbsym5_id = vsp.GetXSecParm(xsec5_id, 'TBSym')
width5_id = vsp.GetXSecParm(xsec5_id,'Super_Width')
height5_id = vsp.GetXSecParm(xsec5_id, 'Super_Height')
secttess5_id = vsp.GetXSecParm(xsec5_id, 'SectTess_U')
xlocpercent5_id = vsp.GetXSecParm(xsec5_id, 'XLocPercent')
zlocpercent5_id = vsp.GetXSecParm(xsec5_id, 'ZLocPercent')
supermaxwidthloc5_id = vsp.GetXSecParm(xsec5_id,'Super_MaxWidthLoc')
superm5_id = vsp.GetXSecParm(xsec5_id,'Super_M')
supern5_id = vsp.GetXSecParm(xsec5_id, 'Super_N')
vsp.SetParmVal(width5_id, 3.45)
vsp.SetParmVal(height5_id, 3.00)
vsp.SetParmVal(secttess5_id, 8)
vsp.SetParmVal(xlocpercent5_id, 0.56)
vsp.SetParmVal(zlocpercent5_id, 0.00025)
vsp.SetParmVal(supermaxwidthloc5_id, 0.0)
vsp.SetParmVal(superm5_id, 3.0)
vsp.SetParmVal(supern5_id, 3.0)
vsp.SetParmVal(tbsym5_id, 0)
vsp.SetParmVal(toplrangleeq5_id, 0)
vsp.SetParmVal(bottomlrangleeq5_id, 0)

# Skinning Left
toplangle5_id = vsp.GetXSecParm(xsec5_id, 'TopLAngle')
toplstrength5_id = vsp.GetXSecParm(xsec5_id, 'TopLStrength')
rightlangle5_id = vsp.GetXSecParm(xsec5_id, 'RightLAngle')
rightlstrength5_id = vsp.GetXSecParm(xsec5_id, 'RightLStrength')
bottomlangle5_id = vsp.GetXSecParm(xsec5_id, 'BottomLAngle')
bottomlstrength5_id = vsp.GetXSecParm(xsec5_id, 'BottomLStrength')
leftlangle5_id = vsp.GetXSecParm(xsec5_id, 'LeftLAngle')
leftlstrength5_id =  vsp.GetXSecParm(xsec5_id, 'LeftLStrength')
vsp.SetParmVal(toplangle5_id, -37.0)
vsp.SetParmVal(toplstrength5_id, 1.06)
vsp.SetParmVal(rightlangle5_id, 0.0)
vsp.SetParmVal(rightlstrength5_id, 1.0)
vsp.SetParmVal(bottomlangle5_id, -22.5)
vsp.SetParmVal(bottomlstrength5_id, 0.50)
vsp.SetParmVal(leftlangle5_id, 0.0)
vsp.SetParmVal(leftlstrength5_id, 1.0)

# Skinning Right
toprangle5_id = vsp.GetXSecParm(xsec5_id, 'TopRAngle')
toprstrength5_id = vsp.GetXSecParm(xsec5_id, 'TopRStrength')
rightrangle5_id = vsp.GetXSecParm(xsec5_id, 'RightRAngle')
rightrstrength5_id = vsp.GetXSecParm(xsec5_id, 'RightRStrength')
bottomrangle5_id = vsp.GetXSecParm(xsec5_id, 'BottomRAngle')
bottomrstrength5_id = vsp.GetXSecParm(xsec5_id, 'BottomRStrength')
leftrangle5_id = vsp.GetXSecParm(xsec5_id, 'LeftRAngle')
leftrstrength5_id =  vsp.GetXSecParm(xsec5_id, 'LeftRStrength')
vsp.SetParmVal(toprangle5_id, 1.0)
vsp.SetParmVal(toprstrength5_id, 1.0)
vsp.SetParmVal(rightrangle5_id, 0.0)
vsp.SetParmVal(rightrstrength5_id, 1.0)
vsp.SetParmVal(bottomrangle5_id, 1.0)
vsp.SetParmVal(bottomrstrength5_id, 2.0)
vsp.SetParmVal(leftrangle5_id, 0.0)
vsp.SetParmVal(leftrstrength5_id, 1.0)
vsp.InsertXSec( fuse_id, 5, vsp.XS_SUPER_ELLIPSE)

# Section 6 of Fuselage
# XSec
xsurf_id = vsp.GetXSecSurf(fuse_id, 6)
xsec6_id = vsp.GetXSec(xsurf_id, 6)
toplrangleeq6_id = vsp.GetXSecParm(xsec6_id, 'TopLRAngleEq')
bottomlrangleeq6_id = vsp.GetXSecParm(xsec6_id, 'BottomLRAngleEq')
tbsym6_id = vsp.GetXSecParm(xsec6_id, 'TBSym')
width6_id = vsp.GetXSecParm(xsec6_id,'Super_Width')
height6_id = vsp.GetXSecParm(xsec6_id, 'Super_Height')
secttess6_id = vsp.GetXSecParm(xsec6_id, 'SectTess_U')
xlocpercent6_id = vsp.GetXSecParm(xsec6_id, 'XLocPercent')
zlocpercent6_id = vsp.GetXSecParm(xsec6_id, 'ZLocPercent')
supermaxwidthloc6_id = vsp.GetXSecParm(xsec6_id,'Super_MaxWidthLoc')
superm6_id = vsp.GetXSecParm(xsec6_id,'Super_M')
supern6_id = vsp.GetXSecParm(xsec6_id, 'Super_N')
vsp.SetParmVal(width6_id, 1.30)
vsp.SetParmVal(height6_id, 1.6)
vsp.SetParmVal(secttess6_id, 20)
vsp.SetParmVal(xlocpercent6_id, 0.90)
vsp.SetParmVal(zlocpercent6_id, 0.0022)
vsp.SetParmVal(supermaxwidthloc6_id, 0.0)
vsp.SetParmVal(superm6_id, 3.0)
vsp.SetParmVal(supern6_id, 3.0)
vsp.SetParmVal(tbsym6_id, 0)
vsp.SetParmVal(toplrangleeq6_id, 0)
vsp.SetParmVal(bottomlrangleeq6_id, 0)

# Skinning Left
toplangle6_id = vsp.GetXSecParm(xsec6_id, 'TopLAngle')
toplstrength6_id = vsp.GetXSecParm(xsec6_id, 'TopLStrength')
rightlangle6_id = vsp.GetXSecParm(xsec6_id, 'RightLAngle')
rightlstrength6_id = vsp.GetXSecParm(xsec6_id, 'RightLStrength')
bottomlangle6_id = vsp.GetXSecParm(xsec6_id, 'BottomLAngle')
bottomlstrength6_id = vsp.GetXSecParm(xsec6_id, 'BottomLStrength')
leftlangle6_id = vsp.GetXSecParm(xsec6_id, 'LeftLAngle')
leftlstrength6_id =  vsp.GetXSecParm(xsec6_id, 'LeftLStrength')
vsp.SetParmVal(toplangle6_id, 1.0)
vsp.SetParmVal(toplstrength6_id, 0.15)
vsp.SetParmVal(rightlangle6_id, 0.0)
vsp.SetParmVal(rightlstrength6_id, 1.0)
vsp.SetParmVal(bottomlangle6_id, 1.5)
vsp.SetParmVal(bottomlstrength6_id, 0.50)
vsp.SetParmVal(leftlangle6_id, 0.0)
vsp.SetParmVal(leftlstrength6_id, 1.0)

# Skinning Right
toprangle6_id = vsp.GetXSecParm(xsec6_id, 'TopRAngle')
toprstrength6_id = vsp.GetXSecParm(xsec6_id, 'TopRStrength')
rightrangle6_id = vsp.GetXSecParm(xsec6_id, 'RightRAngle')
rightrstrength6_id = vsp.GetXSecParm(xsec6_id, 'RightRStrength')
bottomrangle6_id = vsp.GetXSecParm(xsec6_id, 'BottomRAngle')
bottomrstrength6_id = vsp.GetXSecParm(xsec6_id, 'BottomRStrength')
leftrangle6_id = vsp.GetXSecParm(xsec6_id, 'LeftRAngle')
leftrstrength6_id =  vsp.GetXSecParm(xsec6_id, 'LeftRStrength')
vsp.SetParmVal(toprangle6_id, -12.0)
vsp.SetParmVal(toprstrength6_id, 0.65)
vsp.SetParmVal(rightrangle6_id, 0.0)
vsp.SetParmVal(rightrstrength6_id, 0.0)
vsp.SetParmVal(bottomrangle6_id, 0.25)
vsp.SetParmVal(bottomrstrength6_id, 0.0)
vsp.SetParmVal(leftrangle6_id, 0.0)
vsp.SetParmVal(leftrstrength6_id, 1.0)

#Section 7 of Fuselage
# XSec
xsurf_id = vsp.GetXSecSurf(fuse_id, 7)
vsp.ChangeXSecShape(xsurf_id, 7, vsp.XS_SUPER_ELLIPSE)
xsec7_id = vsp.GetXSec(xsurf_id, 7)
toplrangleeq7_id = vsp.GetXSecParm(xsec7_id, 'TopLRAngleEq')
bottomlrangleeq7_id = vsp.GetXSecParm(xsec7_id, 'BottomLRAngleEq')
tbsym7_id = vsp.GetXSecParm(xsec7_id, 'TBSym')
width7_id = vsp.GetXSecParm(xsec7_id,'Super_Width')
height7_id = vsp.GetXSecParm(xsec7_id, 'Super_Height')
secttess7_id = vsp.GetXSecParm(xsec7_id, 'SectTess_U')
zlocpercent7_id = vsp.GetXSecParm(xsec7_id, 'ZLocPercent')
supermaxwidthloc7_id = vsp.GetXSecParm(xsec7_id,'Super_MaxWidthLoc')
superm7_id = vsp.GetXSecParm(xsec7_id,'Super_M')
supern7_id = vsp.GetXSecParm(xsec7_id, 'Super_N')
vsp.SetParmVal(width7_id, 0.0)
vsp.SetParmVal(height7_id, 0.95)
vsp.SetParmVal(secttess7_id, 8)
vsp.SetParmVal(zlocpercent7_id, 0.0072)
vsp.SetParmVal(supermaxwidthloc7_id, 0.0)
vsp.SetParmVal(superm7_id, 2.0)
vsp.SetParmVal(supern7_id, 2.0)
vsp.SetParmVal(tbsym7_id, 0)
vsp.SetParmVal(toplrangleeq7_id, 0)
vsp.SetParmVal(bottomlrangleeq7_id, 0)

# Skinning Left
toplangle7_id = vsp.GetXSecParm(xsec7_id, 'TopLAngle')
toplstrength7_id = vsp.GetXSecParm(xsec7_id, 'TopLStrength')
rightlangle7_id = vsp.GetXSecParm(xsec7_id, 'RightLAngle')
rightlstrength7_id = vsp.GetXSecParm(xsec7_id, 'RightLStrength')
bottomlangle7_id = vsp.GetXSecParm(xsec7_id, 'BottomLAngle')
bottomlstrength7_id = vsp.GetXSecParm(xsec7_id, 'BottomLStrength')
leftlangle7_id = vsp.GetXSecParm(xsec7_id, 'LeftLAngle')
leftlstrength7_id =  vsp.GetXSecParm(xsec7_id, 'LeftLStrength')
vsp.SetParmVal(toplangle7_id, 1.0)
vsp.SetParmVal(toplstrength7_id, 0.15)
vsp.SetParmVal(rightlangle7_id, 0.0)
vsp.SetParmVal(rightlstrength7_id, 1.0)
vsp.SetParmVal(bottomlangle7_id, 1.0)
vsp.SetParmVal(bottomlstrength7_id, 0.50)
vsp.SetParmVal(leftlangle7_id, 0.0)
vsp.SetParmVal(leftlstrength7_id, 1.0)

# Skinning Right
toprangle7_id = vsp.GetXSecParm(xsec7_id, 'TopRAngle')
toprstrength7_id = vsp.GetXSecParm(xsec7_id, 'TopRStrength')
rightrangle7_id = vsp.GetXSecParm(xsec7_id, 'RightRAngle')
rightrstrength7_id = vsp.GetXSecParm(xsec7_id, 'RightRStrength')
bottomrangle7_id = vsp.GetXSecParm(xsec7_id, 'BottomRAngle')
bottomrstrength7_id = vsp.GetXSecParm(xsec7_id, 'BottomRStrength')
leftrangle7_id = vsp.GetXSecParm(xsec7_id, 'LeftRAngle')
leftrstrength7_id =  vsp.GetXSecParm(xsec7_id, 'LeftRStrength')
vsp.SetParmVal(toprangle7_id, 0.10)
vsp.SetParmVal(toprstrength7_id, 1.22)
vsp.SetParmVal(rightrangle7_id, 0.0)
vsp.SetParmVal(rightrstrength7_id, 0.0)
vsp.SetParmVal(bottomrangle7_id, 0.25)
vsp.SetParmVal(bottomrstrength7_id, 0.0)
vsp.SetParmVal(leftrangle7_id, 0.0)
vsp.SetParmVal(leftrstrength7_id, 0.0)

#Wings
wings_id = vsp.AddGeom('WING', fuse_id)

#XForm
vsp.SetParmVal(wings_id,'X_Rel_Location', 'XForm', 6.55)
vsp.SetParmVal(wings_id,'Z_Rel_Location', 'XForm', 2.9)  

#Plan
vsp.SetParmVal(wings_id,'TotalSpan', 'WingGeom', 36.1)
vsp.SetParmVal(wings_id,'TotalChord', 'WingGeom', 5.48)
vsp.SetParmVal(wings_id, "CapUMaxOption",'EndCap', 8)
vsp.SetParmVal(wings_id, 'CapUMaxLength', 'EndCap', 2.9)

#Airfoil NACA 2412
vsp.SetParmVal(wings_id, 'ThickChord', 'XSecCurve_0', 0.12)
vsp.SetParmVal(wings_id, 'Camber', 'XSecCurve_0', 0.02)
vsp.SetParmVal(wings_id, 'CamberLoc', 'XSecCurve_0', 0.4)
vsp.SetParmVal(wings_id, 'ThickChord', 'XSecCurve_1', 0.12)
vsp.SetParmVal(wings_id, 'Camber', 'XSecCurve_1', 0.02)
vsp.SetParmVal(wings_id, 'CamberLoc', 'XSecCurve_1', 0.4)
vsp.InsertXSec(wings_id, 1, 7)
vsp.SetParmVal(wings_id, 'ThickChord', 'XSecCurve_2', 0.12)
vsp.SetParmVal(wings_id, 'Camber', 'XSecCurve_2', 0.02)
vsp.SetParmVal(wings_id, 'CamberLoc', 'XSecCurve_2', 0.4)

#Sect 1
xsurf1_id = vsp.GetXSecSurf(wings_id, 1)
xsec11_id = vsp.GetXSec(xsurf1_id, 1)
tipchord1_id = vsp.GetXSecParm(xsec11_id, 'Tip_Chord')
vsp.SetParmVal(tipchord1_id, 5.98)
rootchord1_id = vsp.GetXSecParm(xsec11_id, 'Root_Chord')
vsp.SetParmVal(rootchord1_id, 5.98)
span1_id = vsp.GetXSecParm(xsec11_id, 'Span')
vsp.SetParmVal(span1_id, 8.8222)
vsp.SetParmVal(wings_id, 'Sweep', 'XSec_1', 0.035)
vsp.SetParmVal(wings_id, 'Dihedral', 'XSec_1', 1.70)

#Sect 2
xsurf1_id = vsp.GetXSecSurf(wings_id, 2)
xsec22_id = vsp.GetXSec(xsurf1_id, 2)
tipchord2_id = vsp.GetXSecParm(xsec22_id, 'Tip_Chord')
vsp.SetParmVal(tipchord2_id, 4.00)
rootchord2_id = vsp.GetXSecParm(xsec22_id, 'Root_Chord')
vsp.SetParmVal(rootchord2_id, 5.98)
span2_id = vsp.GetXSecParm(xsec22_id, 'Span')
vsp.SetParmVal(span2_id, 9.228)
vsp.SetParmVal(wings_id, 'Sweep', 'XSec_2', 5.20)
vsp.SetParmVal(wings_id, 'Dihedral', 'XSec_2', 2.40)

# Horizontal Tail
horztail_id = vsp.AddGeom('WING',fuse_id)
vsp.SetGeomName(horztail_id, 'Horizontal_Tail')

#Xform
vsp.SetParmVal(horztail_id, 'X_Rel_Location', 'XForm', 21.8)
vsp.SetParmVal(horztail_id, 'Z_Rel_Location', 'XForm', 0.57)

#Plan
vsp.SetParmVal(horztail_id,'TotalSpan', 'WingGeom', 11.1)
vsp.SetParmVal(horztail_id,'TotalChord', 'WingGeom', 3.9)
vsp.SetParmVal(horztail_id, "CapUMaxOption",'EndCap', 2)
vsp.SetParmVal(horztail_id, 'CapUMaxLength', 'EndCap', 2.55)

#Sec 1
xsurf2_id = vsp.GetXSecSurf(horztail_id, 1)
xsec111_id = vsp.GetXSec(xsurf2_id, 1)
tipchord11_id = vsp.GetXSecParm(xsec111_id, 'Tip_Chord')
vsp.SetParmVal(tipchord11_id, 2.95)
rootchord11_id = vsp.GetXSecParm(xsec111_id, 'Root_Chord')
vsp.SetParmVal(rootchord11_id, 5.0)
span11_id = vsp.GetXSecParm(xsec111_id, 'Span')
vsp.SetParmVal(span11_id, 5.5)
vsp.SetParmVal(horztail_id, 'Sweep', 'XSec_1', 9.95)

#Airfoil NACA 2412
vsp.SetParmVal(horztail_id, 'ThickChord', 'XSecCurve_0', 0.12)
vsp.SetParmVal(horztail_id, 'Camber', 'XSecCurve_0', 0.02)
vsp.SetParmVal(horztail_id, 'CamberLoc', 'XSecCurve_0', 0.4)
vsp.ChangeXSecShape(xsurf2_id, 1, 11)

# Vertical Tail
verttail_id = vsp.AddGeom('WING',fuse_id)
vsp.SetGeomName(verttail_id, 'Vertical_Tail')

#XForm
vsp.SetParmVal(verttail_id, 'X_Rel_Rotation', 'XForm', 90)
vsp.SetParmVal(verttail_id, 'Z_Rel_Rotation', 'XForm', -4.75)
vsp.SetParmVal(verttail_id, 'X_Rel_Location', 'XForm', 16.5)
vsp.SetParmVal(verttail_id, 'Z_Rel_Location', 'XForm', 1.3)

#Plan
vsp.SetParmVal(verttail_id,'TotalSpan', 'WingGeom', 9.6)
vsp.SetParmVal(verttail_id,'TotalChord', 'WingGeom', 4.3)
vsp.SetParmVal(verttail_id, "CapUMaxOption",'EndCap', 2)
vsp.SetParmVal(verttail_id, 'CapUMaxLength', 'EndCap', 1.0)

#NACA 2412
vsp.SetParmVal(verttail_id, 'ThickChord', 'XSecCurve_0', 0.12)
vsp.SetParmVal(verttail_id, 'Camber', 'XSecCurve_0', 0.02)
vsp.SetParmVal(verttail_id, 'CamberLoc', 'XSecCurve_0', 0.4)
vsp.SetParmVal(verttail_id, 'ThickChord', 'XSecCurve_1', 0.12)
vsp.SetParmVal(verttail_id, 'Camber', 'XSecCurve_1', 0.02)
vsp.SetParmVal(verttail_id, 'CamberLoc', 'XSecCurve_1', 0.4)
vsp.InsertXSec(verttail_id, 1, 7)
vsp.SetParmVal(verttail_id, 'ThickChord', 'XSecCurve_2', 0.12)
vsp.SetParmVal(verttail_id, 'Camber', 'XSecCurve_2', 0.02)
vsp.SetParmVal(verttail_id, 'CamberLoc', 'XSecCurve_2', 0.4)

#Sec 1
xsurf3_id = vsp.GetXSecSurf(verttail_id, 1)
xsec1_1_id = vsp.GetXSec(xsurf3_id, 1)
tipchord1_1_id = vsp.GetXSecParm(xsec1_1_id, 'Tip_Chord')
vsp.SetParmVal(tipchord1_1_id, 3.45)
rootchord1_1_id = vsp.GetXSecParm(xsec1_1_id, 'Root_Chord')
vsp.SetParmVal(rootchord1_1_id, 8.55)
span1_1_id = vsp.GetXSecParm(xsec1_1_id, 'Span')
vsp.SetParmVal(span1_1_id, 1.3)
vsp.SetParmVal(verttail_id, 'Sweep', 'XSec_1', 28.5)
vsp.SetParmVal(verttail_id, 'Sweep_Location', 'XSec_1', 0.99)

#Sect 2
xsurf3_id = vsp.GetXSecSurf(verttail_id, 2)
xsec2_2_id = vsp.GetXSec(xsurf3_id, 2)
tipchord2_2_id = vsp.GetXSecParm(xsec2_2_id, 'Tip_Chord')
vsp.SetParmVal(tipchord2_2_id, 1.71)
rootchord2_2_id = vsp.GetXSecParm(xsec2_2_id, 'Root_Chord')
vsp.SetParmVal(rootchord2_2_id, 3.45)
span2_2_id = vsp.GetXSecParm(xsec2_2_id, 'Span')
vsp.SetParmVal(span2_2_id, 3.5)
vsp.SetParmVal(verttail_id, 'Sweep', 'XSec_2', 25.83)
vsp.SetParmVal(verttail_id, 'Sweep_Location', 'XSec_2', 0.99)

# 2. Using the api, create a prop component and rotate and place it in a reasonable location
prop_id = vsp.AddGeom('PROP', wings_id)
vsp.SetParmVal(prop_id, 'X_Rel_Location', 'XForm', 1.0)
vsp.SetParmVal(prop_id, 'Z_Rel_Location', 'XForm', 0.70)
vsp.SetParmVal(prop_id, 'RadiusFrac', 'XSec_0', 0.15)
vsp.SetParmVal(prop_id, 'Rotate', 'Design', 45.0)

# 3. Using the api, change the number of blades from the default value to another value 
#(say from 3 blades to 5 blades)
vsp.SetParmVal(prop_id, 'Diameter', 'Design', 6.5)
vsp.SetParmVal(prop_id, 'NumBlade', 'Design', 2)

# 4. Using the api, change the blade twist, chord, and thickness distribution 
#(exaggerate them to prove it is working)
# Blade Twist
vsp.SetParmVal(prop_id, 'tw_0', 'Twist', 70.0)
vsp.SetParmVal(prop_id, 'tw_1', 'Twist', 55.0)
vsp.SetParmVal(prop_id, 'tw_2', 'Twist', 45.0)

# Chord
vsp.SetParmVal(prop_id, 'crd_0', 'Chord', 0.07)
vsp.SetParmVal(prop_id, 'crd_1', 'Chord', 0.17)
vsp.SetParmVal(prop_id, 'crd_2', 'Chord', 0.26)
vsp.SetParmVal(prop_id, 'crd_3', 'Chord', 0.27)
vsp.SetParmVal(prop_id, 'crd_4', 'Chord', 0.281)
vsp.SetParmVal(prop_id, 'crd_5', 'Chord', 0.28)
vsp.SetParmVal(prop_id, 'crd_6', 'Chord', 0.28)
vsp.SetParmVal(prop_id, 'crd_7', 'Chord', 0.28)
vsp.SetParmVal(prop_id, 'crd_8', 'Chord', 0.28)
vsp.SetParmVal(prop_id, 'crd_9', 'Chord', 0.28)

# Thickness Distribution
vsp.SetParmVal(prop_id, 'toc_0', 'Thick', 1.0)
vsp.SetParmVal(prop_id, 'toc_1', 'Thick', 0.8)
vsp.SetParmVal(prop_id, 'toc_2', 'Thick', 0.725)
vsp.SetParmVal(prop_id, 'toc_3', 'Thick', 0.70)
vsp.SetParmVal(prop_id, 'toc_4', 'Thick', 0.625)
vsp.SetParmVal(prop_id, 'toc_5', 'Thick', 0.615)
vsp.SetParmVal(prop_id, 'toc_6', 'Thick', 0.60)
vsp.SetParmVal(prop_id, 'toc_7', 'Thick', 0.575)
vsp.SetParmVal(prop_id, 'toc_8', 'Thick', 0.555)
vsp.SetParmVal(prop_id, 'toc_9', 'Thick', 0.530)

# 5. Write out the openvsp file to disk
fname = 'Cessna 172 Skyhawk Mock.vsp3'
vsp.SetVSP3FileName(fname);
vsp.Update()
vsp.WriteVSPFile(vsp.GetVSPFileName(),vsp.SET_ALL );
vsp.ReadVSPFile( fname );